const suggestions = [
  "History of the Roman Empire",
  "How to play guitar",
  "Python basics",
  "Learn calculus",
  "Photography tips",
  "Meditation techniques",
  "Cooking Italian cuisine",
  "Introduction to JavaScript",
  "Yoga for beginners",
  "Gardening tips",
  "Machine learning basics",
  "Painting with watercolors",
  "Digital marketing strategies",
  "How to start a blog",
  "Public speaking tips",
  "Understanding quantum physics",
  "Traveling on a budget",
  "Learning Spanish",
  "Financial planning 101",
  "Time management techniques",
  "How to get better at playing chess",
  "Baking bread at home",
  "Learning HTML and CSS",
  "Self-defense techniques",
  "Basic first aid skills",
  "Investing for dummies",
  "How to write a resume",
  "Mindfulness exercises",
  "Interior design tips",
  "Fitness routines at home",
  "Astronomy for beginners",
  "How to start a YouTube channel",
  "Learning R programming",
  "Sustainable living tips",
  "Mediterranean diet guide",
  "Calligraphy techniques",
  "Learning SQL databases",
  "How to knit",
  "Improving memory skills",
  "Freelancing tips",
  "Speech writing tips",
  "C++ basics",
  "Hiking safety tips",
  "Podcasting essentials",
  "Gardening for small spaces",
  "Social media growth tips",
  "Digital illustration techniques",
  "Mindset for success",
  "Learning French",
  "Basic sewing skills",
  "Photography composition rules",
  "How to make cocktails",
  "Home workout ideas",
  "Understanding blockchain",
  "Origami for beginners",
  "How to start investing",
  "Leadership skills",
  "DIY home projects",
  "Writing short stories",
  "Understanding economics",
  "Music theory basics",
  "Gardening organic vegetables",
  "How to meditate effectively",
  "Learning Excel formulas",
  "Podcast editing tips",
  "How to improve sleep",
  "Learning TypeScript",
  "Travel photography tips",
  "Public relations strategies",
  "How to start coding",
  "Personal branding tips",
  "Introduction to philosophy",
  "Painting landscapes",
  "Learning guitar chords",
  "How to save money",
  "Data science projects",
  "Fitness motivation techniques",
  "Improving concentration",
  "How to create infographics",
  "How to start learning German",
  "Understanding climate change",
  "How to start a startup",
  "Vegan cooking tips",
  "Learning Korean",
  "Graphic design basics",
  "Budget travel hacks",
  "Speed reading techniques",
  "How to build a PC",
  "Learning meditation for stress",
  "Playing piano for beginners",
  "Interior decorating on a budget",
  "Writing a novel",
  "Understanding cryptocurrency",
  "How to run a marathon",
  "Learning Japanese",
  "Tips for public speaking",
  "Self-publishing a book",
  "Building a mobile app",
  "Time blocking techniques",
  "Photography lighting tricks",
  "How to write a cover letter",
  "Learning photography editing",
  "Mindful eating habits",
  "Starting an online business",
  "Learning data visualization",
  "How to journal effectively",
  "Understanding world history",
  "Drawing for beginners",
  "Learning Swift programming",
  "Building a gaming PC",
  "How to invest in real estate",
  "Mastering Excel pivot tables",
  "Learning web development",
  "How to start a podcast",
  "Improving social skills",
  "Writing poetry tips",
  "Understanding statistics",
  "How to build a website",
  "Learning Photoshop",
  "Sustainable fashion tips",
  "Time-saving productivity hacks",
  "How to manage stress",
  "Learning MATLAB",
  "Public speaking confidence",
  "How to do yoga at home",
  "Digital drawing with tablets",
  "Learning PHP programming",
  "How to improve handwriting",
  "Understanding global politics",
  "How to organize your workspace",
  "Learning CSS animations",
  "Tips for healthy eating",
  "How to learn faster",
  "Building a home garden",
  "Learning music composition",
  "How to start freelancing",
  "Personal finance management",
  "Learning mobile photography",
  "How to cook healthy meals",
  "Time management for students",
  "Improving problem-solving skills",
  "How to build a brand",
  "Learning SQL for data analysis",
  "How to decorate small spaces",
  "Tips for creative writing",
  "Learning 3D modeling",
  "How to stay motivated",
  "Understanding psychology",
  "How to start a nonprofit organization",
  "Improving emotional intelligence",
  "Learning video editing",
  "How to train your dog",
  "Tips for better communication",
  "Learning watercolor techniques",
  "How to bake desserts",
  "Starting a fitness journey",
  "Learning C# programming",
  "How to plan a trip",
  "Learning digital marketing",
  "Tips for effective studying",
  "How to write a research paper",
  "Understanding cloud computing",
  "Learning natural language processing",
  "How to design logos",
  "Tips for mindfulness meditation",
  "Learning game development",
  "How to improve creativity",
  "Learning robotics basics",
  "How to create online courses",
  "Tips for financial independence",
  "Learning ethical hacking",
  "How to start a side hustle",
  "Understanding philosophy of science",
  "Learning interior design styles",
  "How to cook traditional Italian recipes",
  "Tips for daily productivity",
  "How to set personal goals",
  "Understanding human anatomy",
  "Learning data science with R",
  "Tips for healthy lifestyle",
  "How to create YouTube content",
  "Learning cloud technologies",
  "How to learn a new language quickly",
  "Tips for stress management",
  "Learning creative coding",
  "How to write engaging blogs"
];

document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.getElementById('searchInput');
    let currentIndex = Math.floor(Math.random() * suggestions.length); // start with random suggestion out of the list
    let charIndex = 0;
    let typingTimeout;

    function typePlaceholder() {
        const currentText = suggestions[currentIndex];
        searchInput.placeholder = currentText.slice(0, charIndex + 1);
        charIndex++;

        if (charIndex < currentText.length) {
            typingTimeout = setTimeout(typePlaceholder, 50); // type next character
        } else {
            // after full text typed, pause then go to next suggestion
            typingTimeout = setTimeout(() => {
                charIndex = 0;
                currentIndex = (currentIndex + 1) % suggestions.length;
                typePlaceholder();
            }, 5000); // 3-second pause at full text
        }
    }

    typePlaceholder(); // start animation

    searchInput.addEventListener('focus', () => {
        clearTimeout(typingTimeout); // pause on focus
    });

    searchInput.addEventListener('blur', () => {
        typePlaceholder(); // continue on non-focus
    });
});


